name: Build and Deploy Node.js to AKS

on:
  push:
    branches:
      - main

env:
  REGISTRY: ${{ secrets.ACR_NAME }}.azurecr.io
  IMAGE_NAME: nodejs-app

jobs:
  build-and-push:
    name: Build and Push Docker image to ACR
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      # Log in to Azure
      - name: 'Log in to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Log in to ACR
      - name: 'Log in to Azure Container Registry'
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build . -t ${{ secrets.ACR_NAME }}.azurecr.io/nodejs-app:latest

      # Push the Docker image to ACR
      - name: Push Docker image to ACR
        run: docker push ${{ secrets.ACR_NAME }}.azurecr.io/nodejs-app:latest

  deploy-to-aks:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # Checkout the repository
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      # Log in to Azure
      - name: 'Log in to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Get AKS credentials
      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing

      # Update Kubernetes deployment with the new image
      - name: 'Deploy to AKS'
        run: |
          kubectl set image deployment/nodejs-app nodejs-app=$REGISTRY/$IMAGE_NAME:latest --record

      # Apply Kubernetes manifests
      - name: 'Apply Kubernetes manifests'
        run: |
          kubectl apply -f Kubernetes/deployment.yaml
          kubectl apply -f Kubernetes/service.yaml
