name: Provision AKS with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6  # Specify the desired Terraform version

      # Step 3: Azure CLI login for authentication
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}

      # Step 4: Initialize Terraform (download required providers and modules)
      - name: Terraform Init
        run: terraform init
        working-directory: terraform  # Specify the path if Terraform files are in a subdirectory

      # Step 5: Run Terraform plan to see the changes that will be made
      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform  # Specify the path if Terraform files are in a subdirectory

      # Step 6: Apply Terraform configuration to provision resources (AKS)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform  # Specify the path if Terraform files are in a subdirectory
